CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    email_verified boolean NOT NULL DEFAULT false
);

CREATE TABLE profiles (
    id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    username text UNIQUE,
    created_at timestamptz DEFAULT now(),
    is_admin boolean NOT NULL DEFAULT false,
    bio text DEFAULT '',
    avatar_color text DEFAULT '#6366f1',
    avatar_image text NOT NULL DEFAULT '' CHECK (length(avatar_image) <= 24000),
    xp integer NOT NULL DEFAULT 0
);

CREATE TABLE riddles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type text NOT NULL CHECK (type IN ('word','number')),
    question text NOT NULL,
    answer_text text,
    answer_number numeric,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    explanation text,
    theme text DEFAULT 'general'
);

CREATE TABLE daily_riddles (
    day_key date PRIMARY KEY,
    riddle_id bigint REFERENCES riddles(id),
    type text NOT NULL CHECK (type IN ('word','number')),
    question text NOT NULL,
    answer_text text,
    answer_number numeric,
    explanation text,
    source text NOT NULL CHECK (source IN ('override_id','override_custom','rotation')),
    created_at timestamptz NOT NULL DEFAULT now(),
    theme text DEFAULT 'general'
);

CREATE TABLE riddle_overrides (
    day_key date NOT NULL,
    theme text NOT NULL DEFAULT 'general',
    riddle_id bigint REFERENCES riddles(id),
    question text,
    type text CHECK (type IN ('word','number')),
    answer text,
    explanation text,
    PRIMARY KEY (day_key, theme)
);

CREATE TABLE riddle_schedule (
    day_key date NOT NULL,
    theme text NOT NULL DEFAULT 'general',
    riddle_id bigint REFERENCES riddles(id),
    type text CHECK (type IN ('word','number')),
    question text,
    answer text,
    explanation text,
    PRIMARY KEY (day_key, theme)
);

CREATE TABLE attempts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES users(id) ON DELETE CASCADE,
    day_key date NOT NULL,
    riddle_id bigint NOT NULL REFERENCES riddles(id),
    guess text NOT NULL,
    result text NOT NULL CHECK (result IN ('correct','low','high','wrong')),
    created_at timestamptz DEFAULT now()
);

CREATE TABLE bans (
    user_id uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    banned boolean NOT NULL DEFAULT false
);

CREATE TABLE site_banner (
    id smallint PRIMARY KEY,
    active boolean NOT NULL DEFAULT false,
    message text,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE race_settings (
    id smallint PRIMARY KEY,
    suspended boolean NOT NULL DEFAULT false,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE race_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    duration integer NOT NULL CHECK (duration IN (30,60,120)),
    level text NOT NULL CHECK (level IN ('easy','med','hard')),
    score integer NOT NULL,
    attempts integer NOT NULL
);

CREATE TABLE achievements_catalog (
    key text PRIMARY KEY,
    title text NOT NULL,
    description text
);

CREATE TABLE user_achievements (
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    key text NOT NULL REFERENCES achievements_catalog(key),
    earned_at timestamptz NOT NULL DEFAULT now(),
    day_key date NOT NULL,
    details jsonb,
    PRIMARY KEY (user_id, key, day_key)
);

CREATE TABLE forum_posts (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    day_key date NOT NULL,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content text NOT NULL CHECK (char_length(content) BETWEEN 1 AND 1000),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE forum_replies (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    post_id bigint NOT NULL REFERENCES forum_posts(id) ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content text NOT NULL CHECK (char_length(content) BETWEEN 1 AND 500),
    created_at timestamptz NOT NULL DEFAULT now()
);
